### ISSUE TITLE
MonadLIO instances

### ISSUE THREAD

**Issue by deian** [scslab/lio#27]
Since MonadLIO was removed from core API, we agreed to export the MonadLIO versions in LIO, so modules for each feature doing this would be good.

**Comment by mf59816** [comment]
I think I was about to ask if you would accept a pull request for this, but what you write sounds a bit more complicated than what I had in mind.  I was just going to, say, lio/LIO/Core.hs, and replace:

    setLabel :: Label l => l -> LIO l ()

with

    setLabel :: MonadLIO l m => Label l => l -> m ()

and similarly for all the rest of this repo (where appropriate).  If that's what you mean, I could do it in the next few days.  If not: could you elaborate?  What do you mean by MonadLIO being removed from core API?  I can still see it there.

**Comment by alevy** [comment]
If I remember correctly, I think the idea was to preserve function signatures in the core modules, but have a separate set of higher level modules that export functions that operate for any `MonadLIO`. This would balance performance for, e.g., library writers with convenience for app writers (since they won't have to add `liftLIO` everywhere)

**Comment by deian** [comment]
@mf59816 we had the same API in a prior version. I think this has gotten annoying enough that the MondaLIO by default approach sounds good to me. So happy to accept a PR :)

**Comment by mf59816** [comment]
Ok, I'm on it!

Is it ok if I "accidentally" remove trailing whitespace?  (-:

**Comment by alevy** [comment]
RE: trailing whitespace, definitely :) I think GitHub has a thing that shows the diff disregarding whitespace changes. Otherwise, it'd be nice to have it in a separate commit just so it's easier to separate code review into style and "might break safety properties" review. But, by all means, go at it!

**Comment by mf59816** [comment]
re whitespace: ok, will do.  thanks.  (:

re monadpeel: i can look into this more, but not this week.  meanwhile i'm greatful if you post any hints and pointers here.

re non-lift-variants: i'll wait for @deian's input, and then do this throughout the code (unless instructed otherwise):

```haskell
setLabelP :: PrivDesc l p => Priv p -> l -> LIO l ()
setLabelP p l = ...

setLabelP' :: (MonadLIO l m, PrivDesc l p) => Priv p -> l -> m ()
setLabelP' p l = liftLIO $ setLabelP p l
```

I'm not particularly fond of the `'`-names, but I can't think of anything better.

**Comment by alevy** [comment]
Yeah, let's wait for @deian's opinion as it's mostly just a performance thing (avoids a v-table lookup). For naming, I would actually suggest using different modules: e.g., a `.Trans` and `.Core` module or something, exactly because `'`-names are pretty confusing and hard to read. In general, I would think that people are unlikely to mix-and-match these functions so importing one module vs another seems pretty straight forward.

**Comment by deian** [comment]
I don't like `'` approach. I'm happy if the core functions  are lifted since usability is a bit more important than (what I suspect to be negligible) performance. But the `.Trans` approach seems very clean as well, so that may be a reasonable balance if we're not cluttering the codebase too much.

RE monadpeel: There should be a commit where I was messing with this as a way to lift catch, but I don't remeber exactly when. I'll dig through in the next few days.

**Comment by mf59816** [comment]
Just want to let you know I haven't forgotten about this.  I hope to add the `.Trans` modules over the next few days.

Before I do that, I will also look into `MonadPeel` and `MonadBaseControl`.  (Would you be generally ok with adding more dependencies for that?  Anything you want to see in particular, or don't?)

more coming up soonish...

**Comment by deian** [comment]
Ah, I would separate out the patches for these 2 especially since reasoning about `MonadBaseControl` is (maybe necessarily) more difficult.

**Comment by deian** [comment]
Also: thanks! :D
